package com.a2stars.parasitologiaemicrobiologia.ListViews;

import com.a2stars.parasitologiaemicrobiologia.Models.Question;
import com.a2stars.parasitologiaemicrobiologia.R;

import java.util.ArrayList;
import java.util.List;

public class LOverSimulate {
    private static List<Question> lquestion = new ArrayList<>();

    public static List<Question> getLquestion() {
        if (lquestion.isEmpty()) {
            Question question = new Question();
            question.setId(1L);
            question.setTema("Parasitoses");
            question.setEnunciado("A Classe Cestoda é composta por vermes chatos em forma de fita, tendo como principais membros os espécimes do gênero Taenia, sendo responsável por causar a teníase em humanos e em outros animais. Sobre a Taenia spp. e suas complicações, assinale o item correto:");
            question.setEnunciado2("");
            question.setA("Podendo ser causada pelas espécies T. solium e T. saginata, a Teníase é caracterizada pela ingesta de carne crua contendo oncosferas dos vermes.");
            question.setB("A Teníase tem como características clínicas, a abdominalgia, perda ponderal de peso, náuseas e astenia, constipação intermitente com evacuações semissólidas rotineiras, cefaleia, sendo em menor número pacientes assintomáticos.");
            question.setC("A Cisticercose é uma complicação exclusiva da T. solium, pois a ingesta de alimentos crus ou mal cozidos contendo cisticercos desse verme, pode expressar a doença em variados sítios, como os olhos, músculos e o cérebro.");
            question.setD("A Cisticercose cerebral é uma das complicações mais conhecidas da T. solium, pois causa síndrome epileptiforme focal, sendo tratada com Fenobarbital.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);

            question = new Question();
            question.setId(2L);
            question.setTema("Parasitoses");
            question.setEnunciado("O complexo Teníase-Cisticercose é definido pelos ciclos evolutivos das tênias que provocam essas enfermidades nos animais. Sobre esse verme e o complexo patológico, marque a alternativa errada:");
            question.setEnunciado2("");
            question.setA("A fase adulta do verme admite somente uma espécie como hospedeiro definitivo, o homem, enquanto em sua forma intermediária, admite o porco como hospedeiro intermediário.");
            question.setB("A transmissão para o ambiente se dá por meio das evacuações de indivíduos previamente infestados e uma falha ou ausência de saneamento sanitário.");
            question.setC("A Cisticercose pode provocar deficiências visuais, ataques epilépticos e entre outros sintomas, já a Teníase pode provocar obstrução espacial de apêndice e ductos pancreático e biliar comum.");
            question.setD("Epidemiologicamente há falta de dados sobre prevalência de teníase, contudo, há uma baixa distribuição no país devido atribuição de boas condições de higiene adotadas.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);

            question = new Question();
            question.setId(3L);
            question.setTema("Parasitoses");
            question.setEnunciado("Sobre a patogenia e patologia da Cisticercose, assinale a incorreta:");
            question.setEnunciado2("");
            question.setA("A sequência clínica de acontecimentos na Neurocisticercose faz com que haja a morte do cisto devido às citocinas inflamatórias e eosinófilos no tecido cerebral, havendo por fim, inflamação e calcificação.");
            question.setB("No músculo cardíaco, pode provocar palpitações, ruídos anormais à ausculta e dispneias, já, quando instalados nos olhos, pode causar deslocamento ou perfuração da retina, reações inflamatórias com opacificação do humor vítreo, culminando em perda de visão.");
            question.setC("Quando em instalação muscular ou subcutânea pode provocar algia, fadiga/astenia e câimbras, podendo, chegar a comprometimento total da musculatura com inatividade muscular.");
            question.setD("Quando em tecido cerebral, as manifestações clínicas dependem de localização, estágio da doença, quantidade, estado clínico, virulência da cepa parasitária e grau de resposta imune ao cisticerco.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(4L);
            question.setTema("Parasitoses");
            question.setEnunciado("Quanto ao diagnóstico do complexo de Teníase-Cisticercose, pode-se afirmar que:");
            question.setEnunciado2("");
            question.setA("O exame parasitológico de fezes (EPF) em 3 amostras é um meio diagnóstico para casos sintomáticos e assintomáticos de Cisticercose.");
            question.setB("A ausência de ovos de Taenia spp. no EPF excluem a possibilidade de infestação por esse verme.");
            question.setC("O diagnóstico de Neurocisticercose se dá por técnicas de imagem e técnicas imunológicas, a primeira buscando nódulos calcificados, e, a segunda, anticorpos em LCR.");
            question.setD("O diagnóstico de Cisticercose é iminentemente laboratorial.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(5L);
            question.setTema("Parasitoses");
            question.setEnunciado("Sobre a Equinococose e a Hidatose, zoonoses classificadas como verminoses que podem ser transmitidas aos seres humanos. Sobre essas doenças, pode-se considerar a alternativa errada:");
            question.setEnunciado2("");
            question.setA("A Equinococose é causada por um platelminto da classe Cestodea, o Echinococcus spp., que tem como hospedeiro definitivo o homem, e hospedeiro intermediário o cão.");
            question.setB("Quando há a infestação por Echinococcus spp. há, no homem, a formação de cistos hidáticos no pulmão e no fígado que podem romper causando anafilaxia, evoluindo para óbito.");
            question.setC("A Hidatose é ocasionada pelo verme Taenia hydatigena que tem como hospedeiro definitivo os cães, podendo infestar o homem, podendo causar hepatite cisticercosa.");
            question.setD("Há uma diferenciação do sítio infeccioso dos cisticercos das tênias, sendo a T. multiceps o cérebro, e, a T. hydatigena o fígado.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(6L);
            question.setTema("Parasitoses");
            question.setEnunciado("Sobre a Hymenopelis nana, podem ser consideradas as afirmativas a seguir. Marque a incorreta:");
            question.setEnunciado2("");
            question.setA("Nessa espécie de tênia, o hospedeiro intermediário é o rato, e, o hospedeiro definitivo é o homem.");
            question.setB("É uma tênia menor e mais comum em homens, tendo como outros hospedeiros, roedores e aves.");
            question.setC("A transmissão pode ocorrer por meio da ingesta de ovos ou por meio da ingesta da pulga do rato.");
            question.setD("O tipo de infestação autóloga é a mais comum, provocando infestações recorrentes.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(7L);
            question.setTema("Parasitoses");
            question.setEnunciado("A tênia do peixe é comum em países que consomem peixes de águas frias e profundas, como o salmão e a carpa. Sendo assim, assinale a alternativa correta:");
            question.setEnunciado2("");
            question.setA("Infestação parasitária causada pelo verme Diphyllobothrium latum que em seu estágio mais primário se desenvolve em mamíferos ou em aves, e, o estágio adulto em copépodes (crustáceos) e peixes.");
            question.setB("O sítio de infestação é o intestino delgado onde se desenvolve suas proglotes e desova essas pelo sistema gastrintestinal do animal.");
            question.setC("A infestação por D. latum pode ocasionar o aumento de muco e inflamação de mucosa intestinal, com espoliação nutricional, que pode evoluir para anemia megaloblástica (espoliação de vitamina B12).");
            question.setD("O diagnóstico pode ser feito pelo resultado positivo de proglótides gravídicas em EPF – 3 amostras, e, em peixes com a biópsia de musculatura com achado de verme adulto.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.b);
            lquestion.add(question);

            question = new Question();
            question.setId(8L);
            question.setTema("Parasitoses");
            question.setEnunciado("O Strongyloides stercoralis tem duas formas patogênicas para o homem, sendo encontrado mundialmente, com elevada prevalência em áreas tropicais e subtropicais, com fácil transmissão (probabilidade alta para autoinfecção), tendência à cronicidade podendo ‟agudizar‟ e disseminar pelo organismo humano. Sobre esse patógeno, assinale a incorreta:");
            question.setEnunciado2("");
            question.setA("A eliminação de larvas rabditóides nas fezes do hospedeiro pode realizar o ciclo partenogenético (infectante) e o ciclo sexuado (vida livre).");
            question.setB("A forma cutânea é discreta em pele e mucosas, não podendo levar a reações de hipersensibilidade; já, a forma pulmonar é presente em todos casos com tosse, dispnéia e crises asmatiformes, não podendo haver hemoptise.");
            question.setC("Epidemiologicamente afeta mais trabalhadores rurais e, em países tropicais, crianças, devido ao solo contaminado e a falta de calçados.");
            question.setD("A forma intestinal pode causar enterite, ulcerações com presença de infecção bacteriana secundária; já a forma disseminada é comum em pacientes imunocomprimidos.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.b);
            lquestion.add(question);

            question = new Question();
            question.setId(9L);
            question.setTema("Parasitoses");
            question.setEnunciado("A Malária ou Paludismo é causada por um protozoário chamado Plasmodium spp., sendo conhecido 4 espécies causadoras de doença ao homem (P. vivax, P. falciparum, P. malarie, P. ovalae). A Malária afeta cerca 300 milhões de pessoas, evoluindo para óbito para mais de 1 milhão de casos. Sobre esse agente patogênico, assinale a alternativa correta:");
            question.setEnunciado2("");
            question.setA("O ciclo de vida dos Plasmodium spp. é caracterizado pela entrada de esporozoítos na circulação sanguínea, após isso há a transformação em merozoítos, sendo seguido por trofozoítos, podendo ir para o baço e entrar em latência em forma de hipnozoítos.");
            question.setB("A reprodução sexuada do protozoário se dá em via sanguínea humana, logo, o homem é o hospedeiro definitivo.");
            question.setC("Com o ato hematofagocítico de fêmeas do gênero Lutzomia spp., há a transmissão do protozoário para os homens e outros animais.");
            question.setD("A transmissão pode ocorrer devido à hematofagia de vetor entomológico, por transmissão acidental e por via congênita, sendo esta última uma forma rara de transmissão.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);

            question = new Question();
            question.setId(10L);
            question.setTema("Parasitoses");
            question.setEnunciado("O verme Trichuris trichiura, também chamado de tricocéfalo, é um patógeno cosmopolita de alta prevalência na população humana e de relação parasitária com a espécie humana de longa data. Há registros de múmias endêmicas da Eurásia com presença de ovos desse parasito em alças intestinais. O verme T. trichiura tem como sítio de infestação o intestino grosso, podendo em infestações mais graves alcançar reto e ânus. Marque a alternativa incorreta:");
            question.setEnunciado2("");
            question.setA("A transmissão desse verme por meio da disseminação de ovos para o ambiente e contaminação de alimentos e água, bem como, a ingesta desses pelo hospedeiro.");
            question.setB("Inflamações mais graves podem causar inflamações retais com indução de resposta autônoma da defecação (tenesmo), que em alguns casos agudos pode evoluir em prolapso retal.");
            question.setC("O diagnóstico desta moléstia é feito por via clínica somente em casos de prolapso retal com presença do verme, ou por via laboratorial com EPF – 3 amostras positivo para T. trichiura.");
            question.setD("Profilaticamente pode ser realizada a educação sanitária e a construção de fossas para redução epidemiológica desse verme na população, não sendo, portanto necessário tratar os pacientes.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);

            question = new Question();
            question.setId(11L);
            question.setTema("Parasitoses");
            question.setEnunciado("A família Ancylostomatidae tem como principais representantes os vermes cilíndricos Ancylostoma duodenale e Necator americanus podendo provocar uma enfermidade chamada Ancilostomíase ou “amarelão”, que é contraída por via percutânea e via oral, tendo transmissão quando há a deposição de ovos no ambiente. Sobre essas doenças, marque a alternativa correta:");
            question.setEnunciado2("");
            question.setA("Na fase aguda de infestação, há a penetração ativa das larvas com trauma tissular que podem ocasionar hiperemia, prurido e edema locais.");
            question.setB("A transmissão em humanos pode ocorrer por via mamária e vertical, bem como, infestação por alimentos e água.");
            question.setC("Classifica-se em grau das lesões pelo número de larvas, pela sensibilidade do hospedeiro e pelo local de penetração do verme.");
            question.setD("Na infestação em intestino pode haver sintomas de aumento de apetite, diarreia explosiva e mucosanguinolenta, já em infestação em pulmões pode haver febre e tosse.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(12L);
            question.setTema("Parasitoses");
            question.setEnunciado("Uma das helmintíases mais frequentes, a Ascaridíase é provocada pelo verme cilíndrico Ascaris lumbricoides, sendo um verme cosmopolita de prevalência variada nas populações. No Brasil, o A. lumbricoides chega a infestar cerca de 90 milhões de pessoas por ano, com altos níveis de parasitismo em zonas rurais e urbanas, principalmente em crianças abaixo dos 12 anos. Assinale a alternativa correta:");
            question.setEnunciado2("");
            question.setA("Maior dos nematódeos do trato digestivo humano, o A. lumbricoides é um verme estenoxeno de aparência macroscópica muito similar ao verme T. solium.");
            question.setB("A ingesta de água e alimentos contaminados, ou deposições subungueais, ou a veiculação aérea (poeira e insetos) fazem parte do processo de contaminação.");
            question.setC("A passagem do parasito pelos pulmões ocasiona a Síndrome de Loeffler, ocasionando edema alveolar, infiltrado basofílico, manifestações alérgicas, febre, bronquite e pneumonia.");
            question.setD("O diagnóstico clínico de Ascaridíase é dado pela eliminação de vermes nas fezes, já o diagnóstico laboratorial é dado por EPF – 3 amostras; exames de imagem não são utilizados.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.b);
            lquestion.add(question);

            question = new Question();
            question.setId(13L);
            question.setTema("Parasitoses");
            question.setEnunciado("O vulgarmente conhecido “Bicho geográfico”, ou Larva Migrans, é causado por um verme cilíndrico chamado A. braziliensi, podendo ser também causado pelo A. caninum, sendo um verme cosmopolita com predomínio em regiões tropicais e subtropicais. Sobre essa doença, marque a errada:");
            question.setEnunciado2("");
            question.setA("A penetração ativa da larva na pele humana faz com que haja reação inflamatória localizada em pessoas sensibilizadas anteriormente, e a progressão da larva pela pele faz com que haja infiltrado eosinofílico pelo trajeto do verme, assim, estabelecendo o nome vulgar do verme.");
            question.setB("As partes mais atingidas nos humanos são MMSS e MMII, podendo atingir mucosa oral pelo hábito de geofagia.");
            question.setC("O diagnóstico clínico não é confiável sendo necessário pedir exames laboratoriais como EPF ou sorológico para A. braziliensi.");
            question.setD("Há uma variante da doença chamada Larva Migrans ocular, sendo ocasionada pelo Toxocara canis, de difícil diagnóstico devido ao EPF negativo (ciclo de vida não se completa no homem).");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(14L);
            question.setTema("Parasitoses");
            question.setEnunciado("A Esquistossomíase ou Esquistossomose é uma doença conhecida vulgarmente por “Barriga d‟água”, devido à ascite volumosa presente nos pacientes. Vermes com dimorfismo sexual amplamente distribuído pelo globo, com presença de hospedeiro intermediário e hospedeiro definitivo. Sobre essa doença, assinale a correta:");
            question.setEnunciado2("");
            question.setA("O ciclo de vida deste parasito se dá pela liberação de ovos perto de represas e lagos com a presença do caramujo do gênero Biomphalaria, sendo assim, os ovos eclodem em cercárias que entram nos caramujos e viram miracídios, formas infectantes, que entram ativamente no homem.");
            question.setB("A forma adulta do verme vive no espaço porta, podendo ir para ramos terminais da V. mesentérica superior para reprodução.");
            question.setC("O diagnóstico clínico pode ofertar planejamento sobre a fase da doença, já o laboratorial pode ser feito por EPF e biópsia estomacal.");
            question.setD("A gravidade da infestação depende de vários fatores, os quais, reposta imune do hospedeiro, estado nutricional, idade, carga parasitária e cepa do parasito.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);

            question = new Question();
            question.setId(15L);
            question.setTema("Parasitoses");
            question.setEnunciado("A Criptosporidíase é uma doença causada pelo protozoário Cryptosporidium parvum, uma doença que gera diarreia em pacientes. Sobre a doença e seu causador, marque a alternativa incorreta:");
            question.setEnunciado2("");
            question.setA("A transmissão se dá preferencialmente por via oral-fecal com transporte dos oocistos.");
            question.setB("Em pacientes HIV/AIDS descontrolados há a manifestação de enterocolite aguda e autolimitada.");
            question.setC("Com a esteatorreia causada pode haver uma espoliação de vitaminas lipossolúveis como as vitaminas K, E, D, A.");
            question.setD("O diagnóstico pode ser feito por meio de EPF – 3 amostras.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.b);
            lquestion.add(question);

            question = new Question();
            question.setId(16L);
            question.setTema("Parasitoses");
            question.setEnunciado("A Enterobíase, ou Oxiuríase é uma doença provocada pelo agente patogênico Enterobius vermicularis, sendo uma doença bastante comum e de natureza benigna. É conhecida popularmente por provocar nos pacientes um prurido anal pela noite, devido à deposição noturna de ovos pela fêmea. Sobre a Oxiuríase, marque a alternativa correta:");
            question.setEnunciado2("");
            question.setA("Parasitose universal mais comum em regiões frias e temperadas, os vermes E. vermicularis são monoxênicos e exclusiva da espécie humana, tendo como ponto de infecção o meio familiar.");
            question.setB("O diagnóstico consiste na clínica de prurido anal associada a hemograma, a qual a eosinofilia constitui grande aporte diagnóstico.");
            question.setC("Em mulheres pode haver a migração do verme para vulva e vagina, ocasionando uma vulvovaginite acompanhada sempre de secreção.");
            question.setD("O prurido anal relatado pelos pacientes se refere à intensa reação inflamatória provocada pelos ovos do parasita quando depositados na pele da região glútea do paciente, podendo evoluir a formações pustulosas exsudativas.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(17L);
            question.setTema("Parasitoses");
            question.setEnunciado("A Fasciolose é uma zoonose proveniente da Europa, ocasionada pelos vermes Fasciola hepatica e F. gigantica, com distribuição mundial e transmissão ao homem por meio da ingesta de animais aquáticos e água contaminada pelo parasito. Sobre esse parasito e a doença que ele provoca, assinale a incorreta:");
            question.setEnunciado2("");
            question.setA("Em infecções agudas, o parasito se hospeda no fígado causando morte de hepatócitos, lesões na superfície hepática e áreas de necrose, levando a cicatrização e inflamação do sítio hepático.");
            question.setB("O diagnóstico por meio de EPF – 3 amostras apresenta bom aporte diagnóstico, uma vez que sempre há a presença dos ovos nas fezes.");
            question.setC("Em infecções crônicas, acima de 7 semanas, o parasito se aloca em vesícula biliar e árvore biliar, podendo haver presença de litíase e hepatomegalia.");
            question.setD("A proteção de mananciais aquáticos da poluição fecal pode favorecer para redução dessa zoonose.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.b);
            lquestion.add(question);

            question = new Question();
            question.setId(18L);
            question.setTema("Parasitoses");
            question.setEnunciado("A Filariose ou “Elefantíase” é uma doença parasitária ocasionada por um nematódeo chamada Wuchereria bancrofti sendo comum nas Américas e na África, sendo comum sua infestação, tendo como prevalência de W. bancrofti 112 milhões de indivíduos atualmente. No Brasil, em 1997, houve a instauração do Programa Nacional de Eliminação da Filariose tendo diminuído bastante os números oficiais dessa parasitose, ficando alguns focos dessa no estado do Pernambuco. Sobre essa parasitose, assinale a incorreta:");
            question.setEnunciado2("");
            question.setA("É uma parasitose exclusiva da espécie humana, contendo como vetor o mosquito Culex spp., tendo como sítio de infestação as vias linfáticas.");
            question.setB("É uma parasitose tem seu ciclo heteroxênico, apresentando fase assexuada nos homens e sexuada nos mosquitos vetores.");
            question.setC("A disfunção linfática ocorre devido a obliteração dos vasos linfáticos pelo nematódeo, fato que provoca o edema correlato.");
            question.setD("Laboratorialmente, pode ser realizada a pesquisa de sangue periférico com o achado para filárias no microscópio.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(19L);
            question.setTema("Parasitoses");
            question.setEnunciado("Paciente E.V.A., 24 anos, profissional do sexo, chega à UBS “Comigo Ninguém Pode” relatando prurido vaginal intenso. À anamnese, paciente relata prurido vaginal intenso de início gradual progressivo há 2 semanas, associado a dispaurenia , disúria e desconforto miccional. Ao exame físico, presença de vulvovaginite extensa. Ao exame especular, leucorreia não fisiológica branca leitosa, com formação de bolhas e fétida, ao se analisar orifício cervical externo, vê-se colo em morango. Segundo a clínica, destaque a doença correta da paciente e o agente patogênico:");
            question.setEnunciado2("");
            question.setA("Candidíase – Candida albicans.");
            question.setB("Leucorreia por Clamídia - Chlamydia trachomatis.");
            question.setC("Tricomoníase – Trichomonas vaginalis.");
            question.setD("Vaginose bacteriana - Gardnerella vaginalis e Mycoplasma hominis.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(20L);
            question.setTema("Parasitoses");
            question.setEnunciado("Homem, 67 anos, chega ao pronto socorro com queixas de dispneias aos pequenos esforços, relatando estar infartando. Depois de institucionalizado e medicado com droga beta-bloqueadora, realiza-se anamnese, o qual paciente relata dispnéia aos pequenos esforços, mal-estar, epigastralgia, disfagia com regurgitações, palpitações e insônia de longas datas. O paciente refere fazer uso de zolpidem (hipnótico) para indução de sono, omeprazol (inibidor da bomba de prótons) para tratamento da disfagia e IECA+ diurético de alça devido HAS diagnosticada no posto de saúde. A conduta adotada foi radiografia contrastada com Bário de tórax, sendo visto a imagem abaixo (figura 1). Paciente, entretanto, teve um episódio de arritmia não controlável e evoluiu para PCR com óbito após RCP. Ao exame necrópsico, paciente apresentava cardiomegalia, sendo extraídos fragmentos para biópsia. O resultado dessa biópsia (figura 2) revela ninho de amastigotas. Assinale a afirmativa cuja doença encaixa com a clínica do paciente:");
            question.setEnunciado2("");
            question.setA("Doença de Chagas.");
            question.setB("Endocardite de Libman-Sacks.");
            question.setC("Cardiopatia e esofagopatia lúpica.");
            question.setD("Endocardite por Streptococcus mutans.");
            question.setFoto(R.drawable.parasitoses);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(21L);
            question.setTema("Micoses");
            question.setEnunciado("Sobre as micoses superficiais estritas, marque a alternativa correta:");
            question.setEnunciado2("");
            question.setA("São micoses que atacam a camada mais externa da derme, o estrato queratínico, bem como, a cutícula do pelo.");
            question.setB("Apresentam resposta imune franca, porém o hospedeiro é assintomático.");
            question.setC("Em indivíduos imunocomprometidos, as micoses superficiais estritas podem evoluir para outras camadas da pele, mas não ultrapassa a camada basal.");
            question.setD("As doenças mais comuns são o “pano branco”, a piedra branca e preta, e, a paracoccidiodomicose.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(22L);
            question.setTema("Micoses");
            question.setEnunciado("A Pitiríase versicolor é uma micose estrita à camada córnea dérmica sendo causada pelo fungo do gênero Malassezia spp. Sobre a micose dita, assinale a afirmativa incorreta:");
            question.setEnunciado2("");
            question.setA("A pitiríase versicolor também chamada de “dematomicose furfurácea”, com clínica de máculas hipo/hiperpigmentadas, assimétricas em tronco, pescoço e face.");
            question.setB("É uma micose ubíqua, mais prevalente no sexo masculino e em adultos brancos de zona de elevada incidência solar.");
            question.setC("O diagnóstico é predominantemente clínico com presença dos sinais de Besnier e de Zileri, bem como, fluorescência verde-amarelada ao uso da lâmpada de Wood.");
            question.setD("O diagnóstico rápido também pode ser feito laboratorialmente sob coleta em KOH e cultura em Ágar Sabouraud.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);

            question = new Question();
            question.setId(23L);
            question.setTema("Micoses");
            question.setEnunciado("A Tinea nigra é uma feohifomicose, cujo agente etiológico é a Hortae werneckii, acometendo as regiões palmar e plantar de um indivíduo. Assinale a alternativa correta:");
            question.setEnunciado2("");
            question.setA("A clínica desta micose se baseia em lesões hiperemiadas, descamativas, bem delimitadas, pruriginosas e com edema associado.");
            question.setB("Atinge mais crianças e jovens abaixo de 20 anos e mais o sexo masculino.");
            question.setC("O diagnóstico pode ser feito por meio da coleta do raspado de bordos e visualização do fungo, bem como, exposição deste ao KOH 20%.");
            question.setD("O diagnóstico laboratorial por cultura fúngica com material seletivo para esse tipo de ser vivo, o Ágar Sangue.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(24L);
            question.setTema("Micoses");
            question.setEnunciado("A Piedra preta tem como agente etiológico o ascomiceto Piedraia hortae, que causa tal enfermidade nos pelos, podendo ser chamada também de “Tricomicose nodosa escura” ou “Tricomicose dos estudantes”. Sobre essa micose, marque a alternativa correta:");
            question.setEnunciado2("");
            question.setA("Há envolvimento patológico do folículo piloso, que cursa com alopecia bem delimitada ao campo de acometimento fúngico.");
            question.setB("A clínica dessa enfermidade é o aparecimento de nódulos escuros e endurecidos aderidos aos cabelos e outro pelos.");
            question.setC("Tem alto poder de contágio, assintomático, crônico e recidivante, sendo mais frequente em indivíduos do sexo masculino.");
            question.setD("O diagnóstico laboratorial pode ser feito pela coleta e exame direto com KOH 20% - com presença de hifas dermáceas – e coleta e exame cultural em Ágar Sangue – com presença de colônia preta ou verde escura com elevação central.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.b);
            lquestion.add(question);

            question = new Question();
            question.setId(25L);
            question.setTema("Micoses");
            question.setEnunciado("A Piedra branca é uma hialohifomicose, ocasionada por uma levedura do gênero Trichosporon spp. Sobre essa enfermidade, assinale a incorreta:");
            question.setEnunciado2("");
            question.setA("Há envolvimento do pelo com aparecimento de nódulos claros e moles principalmente na região púbica.");
            question.setB("Pode evoluir de assintomático para sintomático, ocasionando lesões cutâneas hiperemiadas na base do folículo piloso.");
            question.setC("Atinge mais a homens e tem como tratamentos antifúngicos orais e tricotomia.");
            question.setD("O diagnóstico em exame direto com KOH 20% é visto nódulos castanhos claros com massa de leveduras hialinas; já, em exame cultural, observa-se colônia cremosa, leveduriformes, de cor bege-amarelada.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(26L);
            question.setTema("Micoses");
            question.setEnunciado("As micoses cutâneas ou dermatofitoses são principalmente ocasionadas pelos dermatófitos, que são fungos filamentosos hialinos capazes de digerir a queratina presente em pele e fâneros humanos. Sobre essas micoses e seus agentes etiológicos, cite a alternativa incorreta:");
            question.setEnunciado2("");
            question.setA("Os principais gêneros patógenos nas dermatofitoses são Trichophyton spp., Microsporum spp., e, Epidermophyton spp.");
            question.setB("Os artroconídeos só conseguem iniciar a infecção se houver uma porta de entrada na pele.");
            question.setC("Micose mais prevalente em mulheres, e, ubíqua com variação de espécies ao redor do globo.");
            question.setD("Idade, gênero, imunocomprometimento, hábitos em geral e migrações são fatores predisponentes para as dermatofitoses.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(27L);
            question.setTema("Micoses");
            question.setEnunciado("Ainda sobre as dermatofitoses, assinale a correta:");
            question.setEnunciado2("");
            question.setA("A pele glabra, ou, “pele sem pelos”, pode ser classificada de acordo com a região de acometimento da lesão em pelos corporais ou unhas.");
            question.setB("A transmissão da tinea pedis, ou tinha das mãos, pode ocorrer devido ao fenômeno “two feet-one hand syndrome.");
            question.setC("A micose Tokelau, que é caracterizada por lesões escamosas muito contagiosas que formam desenhos concêntricos, que são usados pelos indígenas do Pacífico e no Brasil para adorno corporal, pode ser considerada doença.");
            question.setD("A Tinea capitis é mais prevalente em crianças na puberdade, pois os hormônios esteróides são ativadores da multiplicação fúngica.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(28L);
            question.setTema("Micoses");
            question.setEnunciado("As micoses subcutâneas são normalmente causadas por fungos saprófitos habituais do solo e organismo vegetais em decomposição. Geralmente acessam o corpo humano por meio de um trauma prévio ou adjacente a ele. Considere as afirmativas abaixo e assinale a incorreta:");
            question.setEnunciado2("");
            question.setA("A infecção depende principalmente da resistência do hospedeiro, da virulência da cepa fúngica e da quantidade de material patogênico inoculado.");
            question.setB("As lesões tendem a cronicidade, e, em indivíduos com imunocomprometimento, pode haver fungemia.");
            question.setC("O tratamento pode ocorrer ambulatorialmente com antifúngicos orais ou tópicos, ou, cirurgicamente.");
            question.setD("As lesões normalmente ocorrem nos MMII e nos MMSS.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);

            question = new Question();
            question.setId(29L);
            question.setTema("Micoses");
            question.setEnunciado("A Esporotricose é ocasionada por um fungo dimórfico Sporothrix spp., é considerada uma micose ocupacional, pois atinge mais a trabalhadores de jardinagem, mineração e agricultura. Sobre essa micose, assinale a alternativa incorreta:");
            question.setEnunciado2("");
            question.setA("É uma micose endêmica – América do Sul – que acomete mais aos indivíduos do sexo masculino.");
            question.setB("O diagnóstico pelo exame direto fecha diagnóstico devido forte evidência, quando visualizado corpos leveduriformes semelhantes a charuto.");
            question.setC("A clínica da Esporotricose é característica de uma doença crônica granulomatosa que surge de 1-12 semanas após exposição, de cor róseo-avermelhada, podendo evoluir com ulceração e disseminação linfática.");
            question.setD("O diagnóstico pela cultura do Sporothrix spp. e visualização dos corpos de frutificação semelhantes à margaridas tem maior fator diagnóstico.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.b);
            lquestion.add(question);

            question = new Question();
            question.setId(30L);
            question.setTema("Micoses");
            question.setEnunciado("A Cromomicose é uma micose granulomatosa crônica subcutânea ocasionada pela entrada de fungos demáceos em locais de trauma prévio ou adjacente. Sobre essa micose, assinale a incorreta:");
            question.setEnunciado2("");
            question.setA("Os fungos demáceos mais comuns na Cromomicose são os Fonsecaea pedrosoi e Cladophialophora carrionii.");
            question.setB("Atinge mais a homens por motivos laborais, e, mais em países tropicais ou subtropicais.");
            question.setC("A clínica do paciente com Cromomicose é característico de lesões em “aspecto de couve flor”.");
            question.setD("Ao exame direto com fins diagnósticos, observam-se invasões por hifas.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);

            question = new Question();
            question.setId(31L);
            question.setTema("Micoses");
            question.setEnunciado("Sobre a Feohifomicose, assinale a correta:");
            question.setEnunciado2("");
            question.setA("É ocasionada por fungos oportunistas ubíquos principalmente em zonas rurais.");
            question.setB("Seu ciclo evolutivo se destaca em 3 partes, sendo elas, a colonização superficial, a implantação por trauma e por fim, a infecção restrita ao espaço córneo da derme.");
            question.setC("A lesão cística encapsulada e subcutânea presente na micose pode levar a um quadro sistêmico podendo ser fatal em pacientes imunocompetentes.");
            question.setD("No exame anatomopatológico, vê-se hifas demáceas septadas em meio de transudato.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(32L);
            question.setTema("Micoses");
            question.setEnunciado("Sobre a Lobomicose e Rinosporidiose, assinale a incorreta:");
            question.setEnunciado2("");
            question.setA("Lobomicose é uma micose subcutânea crônica, mais prevalente em homens entre 20-40 anos, devido questão laboral.");
            question.setB("O diagnóstico de Lobomicose é feito por imunofluorescência direta e vê-se cadeias pigmentadas de células leveduriformes.");
            question.setC("A Rinosporidiose é uma micose granulomatose crônica, não transmitível entre humanos.");
            question.setD("A clínica da Rinosporidiose é marcada por grandes pólipos, tumores, papilomas e lesões verrucosas na região nasal, sendo transmitido entre humanos.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);

            question = new Question();
            question.setId(33L);
            question.setTema("Micoses");
            question.setEnunciado("A Paracoccidioidomicose é uma micose sistêmica causada pelo fungo Paracoccidioies brasiliensis, seu contágio se dá por meio da inalação de conídeos, afetando mais a população campesinata masculina de 30 a 50 anos. São características clínicas e diagnósticas, exceto:");
            question.setEnunciado2("");
            question.setA("Forma aguda: acometimento osteoarticular, hepatoespleno-linfadenomegalia e lesões cutâneas.");
            question.setB("Forma crônica: tuberculose com calcificação pulmonar, lesões ulcerativas e hipo/hiperplasia de mucosa.");
            question.setC("O teste padrão-ouro é o isolamento do agente etiológico por exame a fresco de escarro, raspado de bordo lesional, PAAF, fragmento de biópsia.");
            question.setD("No diagnóstico por exame direto com KOH 20%, pode-se ver morfologia “roda de leme”, com presença de células filamentosas arredondadas.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);

            question = new Question();
            question.setId(34L);
            question.setTema("Micoses");
            question.setEnunciado("A Coccidioidomicose é uma micose causada pelo fungo Coccidioides immitis, com ampla distribuição geográfica nas Américas. Marque a alternativa incorreta:");
            question.setEnunciado2("");
            question.setA("As formas de acometimento do fungo são pulmonar, disseminada – em pacientes imunocomprometidos – e, inoculação primária.");
            question.setB("O hábitat do fungo é caracterizado por solos de clima frio com alta salinidade e ph alcalino.");
            question.setC("A transmissão desse fungo se dá pela inalação de artroconídios.");
            question.setD("No exame direto diagnóstico se podem ver elementos espessos esféricos repletos de endósporos.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.b);
            lquestion.add(question);

            question = new Question();
            question.setId(35L);
            question.setTema("Micoses");
            question.setEnunciado("A Histoplasmose é uma micose causada pelo fungo Histoplasma capsulatum com distribuição geográfica mundial. Desse modo, marque a alternativa correta:");
            question.setEnunciado2("");
            question.setA("O hábitat desse fungo é em solos enriquecidos de fezes de aves e morcegos, e, a transmissão se dá pela inalação de conídios.");
            question.setB("A forma pulmonar se divide em dois momentos, a fase aguda – nódulos calcificados – e a fase crônica – cavitações pulmonares com aumento do volume residual pulmonar e macicez à percussão.");
            question.setC("O diagnóstico laboratorial por exame direto encontra pequenas hifas encapsuladas.");
            question.setD("O teste sorológico com histoplasmina se considera positivo com presença somente de eritema.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(36L);
            question.setTema("Micoses");
            question.setEnunciado("A Criptococose é uma micose ocasionada pelo fungo Cryptococcus neoformans, tendo como fatores predisponentes grandes aglomerados populacionais de pombos, ventilação insatisfatória, limpeza inadequada e temperatura elevada. Costuma atacar órgãos profundos e pele, mas tem tropismo pelo SNC. Desse modo, assinale a alternativa verdadeira:");
            question.setEnunciado2("");
            question.setA("É uma das principais doenças, mesmo com as variantes, a atingir pacientes imunocompetentes.");
            question.setB("As manifestações clínicas dos pacientes com Criptococose são assintomática, pulmonar, neurológica e disseminada.");
            question.setC("São fatores negativos de virulência a presença de cápsula, ação da fenoloxidase e da urease.");
            question.setD("O teste ELISA não é eficaz no diagnóstico de Criptococose.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.b);
            lquestion.add(question);

            question = new Question();
            question.setId(37L);
            question.setTema("Micoses");
            question.setEnunciado("A Blastomicose é causada pelo fungo Blastomyces dermatitidis e seu hábitat é em solos úmidos e na presença de organismos vegetais em decomposição. Sobre essa micose, assinale a alternativa incorreta:");
            question.setEnunciado2("");
            question.setA("É frequentemente associado a homens negros na faixa de 30-60 anos de idade.");
            question.setB("Seu local de infecção primária é no tecido pulmonar, onde pode se disseminar por via hematogênica.");
            question.setC("No exame direto, observa-se gêmulos arredondados de parede espessa.");
            question.setD("A evolução pode atingir pele, ossos ou outros órgãos.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(38L);
            question.setTema("Micoses");
            question.setEnunciado("Sobre a Candidose, assinale a incorreta:");
            question.setEnunciado2("");
            question.setA("Ataca pacientes imunocomprometidos.");
            question.setB("Podem ocasionar infecção hospitalar.");
            question.setC("Apresenta diagnóstico claro.");
            question.setD("É primariamente uma infecção endógena.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(39L);
            question.setTema("Micoses");
            question.setEnunciado("Paciente A.A.A, homem, negro, 60 anos, aposentado rural -antes da reforma na previdência-, chega à unidade de saúde referindo “dor de cabeça há 20 dias”. Ao exame clínico, paciente refere cefaleia “em cinturão” progressiva, refratária à dipirona sódica, paracetamol e AAS. Quando arguido sobre outros sintomas refere fadiga, cervicalgia leve, irritabilidade, sonolência diurna excessiva e náusea acompanhada de vômito. Ao exame físico, paciente BEG, normocorado, hidratado, irritadiço e confuso. Quando questionado sobre hábitos sociais rotineiros, paciente relata ida ao parque municipal todo dia pela manhã para alimentar pombos Tax: 37ºC, PA: 130x 90 mmHg, FC: 88 bpm, FR: 16 irpm. À campimetria, observou-se perda da acuidade visual em campo temporal do olho direito. Quando realizado manobra de avaliação da rigidez nucal, detectou-se sinal de Lasègue presente. Examinador solicita neuroimagem e institucionaliza paciente devido risco psicossocial. A seguir, a neuroimagem do paciente AAA:");
            question.setEnunciado2("Baseado na história clínica do paciente dê o diagnóstico provável e o nome do agente etiológico:");
            question.setA("Neurocriptococose – Criptococcus neoformans.");
            question.setB("Cisticercose cerebral – Taenia solium.");
            question.setC("Malária cerebral – Plasmodium vivax");
            question.setD("Esporotricose cerebral – Sporothrix spp.");
            question.setFoto(R.drawable.micoses);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(40L);
            question.setTema("Viroses");
            question.setEnunciado("Sobre o Vírus da Imunodeficiência Humana (HIV), pode-se afirmar que:");
            question.setEnunciado2("");
            question.setA("O HIV está presente sob dois sorotipos, o HIV-1 e o HIV-2, que são igualmente prevalentes mundialmente.");
            question.setB("O HIV é um vírus de RNA – retrovírus –, que tem em sua estrutura envelope viral, responsável pela ligação ao sítio de ligação.");
            question.setC("Tem como fatores de risco biológicos a concentração viral do HIV no fluido, a integridade da mucosa, o tempo de exposição e o sorotipo viral.");
            question.setD("Tem como fatores de risco comportamentais a múltipla parceria sexual, a atividade sexual desprotegida, o uso de drogas EV, bem como, os grupos sociais de risco.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(41L);
            question.setTema("Viroses");
            question.setEnunciado("A Síndrome da Imunodeficiência Adquirida (AIDS) tem manifestações clínicas fase-dependentes, sendo divididas em infecção aguda, crônica assintomática e crônica sintomática. Marque a alternativa incorreta:");
            question.setEnunciado2("");
            question.setA("O quadro clínico característico da infecção aguda é a confluência de sintomas inespecíficos, similar a um quadro gripal.");
            question.setB("Na clínica crônica assintomática há um acontecimento chamado “janela imunológica”, caracterizado como o período de produção de anticorpos anti-HIV.");
            question.setC("Na clínica crônica sintomática há um aumento de linfócitos e uma redução da viremia.");
            question.setD("A fase virêmica crônica sintomática é subdividida didaticamente em inicial, intermediária e tardia, tendo a contagem de linfócitos como parâmetro.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(42L);
            question.setTema("Viroses");
            question.setEnunciado("O paciente com infecção por HIV/AIDS tem, por meio do Sistema Único de Saúde (SUS), apoio em amplas esferas. A se destacar, o atual tratamento para HIV/AIDS preconizado é a Terapia Antirretroviral (TARV) preferencialmente por Tenofovir, Lamivudina e Dolutegravir. Entretanto, algumas doenças podem se instalar devido à linfocitopenia grave. São exemplos de doenças bacterianas associadas à infecção prévia por HIV:");
            question.setEnunciado2("");
            question.setA("Leucoplasia oral pilosa, sífilis e tuberculose.");
            question.setB("Dermatofitoses, condilomas acuminados e angiomatose bacilar.");
            question.setC("Sífilis, tuberculose e angiomatose bacilar.");
            question.setD("Molusco contagioso, verrugas e piodermites.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(43L);
            question.setTema("Viroses");
            question.setEnunciado("O Papilomavírus Humano (HPV) é um vírus da família Papovaviridae que apresenta mais de 200 sorotipos conhecidos, sendo alguns com grande potencial oncogênico. Dessa forma, pode-se afirmar que:");
            question.setEnunciado2("");
            question.setA("O HPV é um vírus de DNA que apresenta grande hepatotropismo.");
            question.setB("Os sorotipos 6 e 11 têm grande potencial oncogênico.");
            question.setC("Os sorotipos 16 e 18 provocam as verrugas genitais.");
            question.setD("A vacinação é um meio eficaz de promover auxílio contra o câncer de colo de útero e o câncer de orofaringe.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);

            question = new Question();
            question.setId(44L);
            question.setTema("Viroses");
            question.setEnunciado("Sobre a infecção por HPV, assinale a afirmativa correta:");
            question.setEnunciado2("");
            question.setA("A transmissão se dá normalmente por contato direto, ou seja, pela via sexual.");
            question.setB("São manifestações clínicas, as verrugas cutâneas, as lesões orais, o papiloma sublingual e as verrugas anogenitais.");
            question.setC("As lesões orais são assintomáticas e evoluem para malignidade.");
            question.setD("As verrugas cutâneas e anogenitais são ocasionadas pelos mesmos sorotipos do HPV.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(45L);
            question.setTema("Viroses");
            question.setEnunciado("Sobre os métodos preventivos contra o HPV, destacam-se o uso de preservativos e a vacinação. Sobre esses métodos, assinale a verdadeira.");
            question.setEnunciado2("");
            question.setA("O uso de camisinhas é dispensável após a administração vacinal.");
            question.setB("A vacinação é o meio mais seguro e eficaz contra as formas com potencial oncogênico do HPV, sendo esses, os sorotipos 6 e 18.");
            question.setC("A camisinha, método de barreira mais eficaz, deve ser usada mesmo que a outra parceria tenha HPV.");
            question.setD("A vacinação contra o HPV atualmente se dá em meninas de 9 a 15 anos, meninos de 12 a 13 anos, e, em pacientes imunocomprometidos de 9 a 26 anos.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(46L);
            question.setTema("Viroses");
            question.setEnunciado("Sobre as hepatites virais, assinale a incorreta.");
            question.setEnunciado2("");
            question.setA("Atualmente, são conhecidos 5 tipos de hepatite classificadas de A a E, sendo 2 de transmissão oral-fecal e 3 por via hemática.");
            question.setB("Podem ocasionar sintomas inespecíficos, os quais, astenia, abdominalgia, vômito/tontura, febre e icterícia.");
            question.setC("Os subtipos A e E apresentam tratamento sintomático, enquanto, os subtipos B, C e D cronificam e são assintomáticos em sua maior parte.");
            question.setD("Todas as hepatites virais apresentam vacinação disponível.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);

            question = new Question();
            question.setId(47L);
            question.setTema("Viroses");
            question.setEnunciado("Ainda sobre as hepatites, assinale a correta:");
            question.setEnunciado2("");
            question.setA("O HAV é um vírus envelopado, RNA fita simples, transmitido por via oral-fecal e podem apresentar sintomas como febre, cefalalgia, mal-estar generalizado e icterícia.");
            question.setB("O HBV é um vírus não envelopado, DNA fita dupla, sendo transmitido por via hemática, sexual e transplacentária, tem tendência à cronicidade – evolução para hepatocarcinoma.");
            question.setC("O HCV é um vírus envelopado, RNA fita simples, sendo transmitido por via hemática, sexual e transplacentária, tem tendência à cronicidade.");
            question.setD("O HDV é um vírus RNA fita dupla, tende a haver coinfecção HBV-HDV, sendo caracterizado por infecção aguda autorresoluta.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.c);
            lquestion.add(question);

            question = new Question();
            question.setId(48L);
            question.setTema("Viroses");
            question.setEnunciado("As viroses dermotrópicas são conhecidas por serem infecções virais com predileção aos sítios mucocutâneos, ou seja, vírus com restrição à superfície corpórea e/ou vírus de ataque sistêmicos com instalação na pele. Destacam-se os vírus da família Herpesviridae, os Herpes-Vírus Humano (HHV) com sorotipos de 1 a 7. Sobre as propriedades dos HHV, assinale a correta:");
            question.setEnunciado2("");
            question.setA("São vírus envelopados com genoma de DNA fita dupla, ubíquos e reproduzem-se por meio da DNA pol.");
            question.setB("HHV são vírus muito prevalente entre os humanos, tendo alta distribuição, patogenicidade e mortalidade.");
            question.setC("Os sorotipos conhecidos atualmente são subdivididos em relação à sua patogenia e ao sítio de infecção.");
            question.setD("São vírus envelopados com genoma de DNA fita dupla, ubíquos e reproduzem-se por meio da RNA pol.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(49L);
            question.setTema("Viroses");
            question.setEnunciado("O HHV-1 e o HHV-2 são subdivididos conjuntamente devido ao mesmo mecanismo patogênico, assim sendo, assinale a alternativa incorreta:");
            question.setEnunciado2("");
            question.setA("É uma virose orogenital transmitida por via sexual quando há o contato direto com lesões ou fômites.");
            question.setB("O sítio inicial de infecção são as células mucoepiteliais, causando inflamação local, e, após isso infectam latentemente o neurônio local, por meio de ciclo lisogênico.");
            question.setC("O DNA viral não está totalmente silenciado devido à ação do RNA LATs.");
            question.setD("O ciclo lítico faz com que os vírus fiquem em modo de latência, enquanto que o ciclo lisogênico faz com que os vírus se multipliquem e lisem a célula.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);

            question = new Question();
            question.setId(50L);
            question.setTema("Viroses");
            question.setEnunciado("Sobre os herpes orogenital, assinale a correta:");
            question.setEnunciado2("");
            question.setA("O HHV-1 é responsável pela infecção latente dos Nn. Lombossacrais, já o HHV-2 é responsável pela infecção latente do N. Trigêmeo.");
            question.setB("A latência do vírus HHV ocorrida em resposta à reação imune é findada quando há imunocomprometimento ou situações de estresse pelo hospedeiro.");
            question.setC("Apresentam em primo-infecção clínica com lesões intermitentes vesiculosas eritematosas com ardência, algia local e prurido associados que evoluem com queixas de ulcerações exsudativas em sítio de infecção de hospedeiro imunocompetente.");
            question.setD("Em mulheres que apresentam cervicite por HHV-1, há risco de contaminação do neonato, que podem evoluir para óbito.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.b);
            lquestion.add(question);

            question = new Question();
            question.setId(51L);
            question.setTema("Viroses");
            question.setEnunciado("A varicela é resultante pela infecção do HHV-3, um vírus de RNA, altamente contagioso, de rápida evolução e caráter benigno. Sobre as doenças que esse patógeno pode causar, assinale a incorreta:");
            question.setEnunciado2("");
            question.setA("A varicela é caracterizada por lesões pruriginosas eritematosas de corpo inteiro que atingem a população pediátrica, não havendo vacina.");
            question.setB("No cobreiro, há um retorno da doença ocasionado pelo HHV-3, devido a um imunocomprometimento do hospedeiro, sendo caracterizado por lesões pruriginosas localizadas em tronco.");
            question.setC("Algumas complicações conhecidas são as infecções bacterianas secundárias, devido a produção de soluções de continuidade pela ação pruriginosa.");
            question.setD("A síndrome de Reye é uma complicação comum quando há contaminação por varicela vírus e há o uso de salicilatos para controle de febre e dor.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.a);
            lquestion.add(question);

            question = new Question();
            question.setId(52L);
            question.setTema("Viroses");
            question.setEnunciado("Sobre as viroses congênitas, assinale a correta:");
            question.setEnunciado2("");
            question.setA("O CMV é um vírus DNA fita simples, da família Herpesviridae, que quando transmitido verticalmente, pode ser fatal ao feto.");
            question.setB("A doença da inclusão citomegálica é uma virose ocasionada pelo CMV, caracterizada semiologicamente pelo sinal “olhos de coruja”.");
            question.setC("O Parvovírus B19 é o agente etiológico da “quinta doença”, caracterizada por eritema bolhoso, em gestantes, pode causar perda fetal por hidropsia (edema) fetal.");
            question.setD("A rubéola é um vírus envelopado de RNA fita simples, que quando presente em gestantes, os neonatos apresentam tríade clínica que consiste em cataratas, cardiopatias congênitas e surdez óssea.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.b);
            lquestion.add(question);

            question = new Question();
            question.setId(53L);
            question.setTema("Viroses");
            question.setEnunciado("Sobre as viroses multissistêmicas, assinale a incorreta:");
            question.setEnunciado2("");
            question.setA("O Sarampo é provocado por um vírus RNA fita simples, cuja vacina é disponibilizada pelo SUS, e, o Brasil até 2016 não apresentava nenhum surto dessa doença.");
            question.setB("O vírus do sarampo provoca uma doença cujo sinal patognomônico é o sinal de Koplik, sendo pequenas manchas hipocoradas com halo eritematoso.");
            question.setC("O vírus da caxumba é um vírus envelopado, RNA fita simples, cuja transmissão ocorre por meio de perdigotos, com período de incubação pequeno.");
            question.setD("A Caxumba ocasiona desconforto respiratório, cefalagia, mal-estar generalizado, anorexia, parotite e febre baixa.");
            question.setFoto(R.drawable.transparent);
            question.setGabarito(R.id.d);
            lquestion.add(question);
        }
        return lquestion;
    }
}